// templates/ng-template/src/app/pages/home-page/home-page.component.ts
import { Component, OnInit } from '@angular/core';
import { LoaderComponent } from '../../ui/loader/loader.component';
import { RootStoreService } from '../../services/root-store.service';
import {
  PlacementStoreService,
  IList,
} from '../../services/placement-store.service';
import { environment } from '../../../environments/environment';
import { UserListsComponent } from '../../components/user-lists/user-lists.component';

@Component({
  selector: 'app-home-page',
  standalone: true,
  imports: [LoaderComponent, UserListsComponent],
  templateUrl: './home-page.component.html',
  styleUrl: './home-page.component.scss',
})
export class HomePageComponent implements OnInit {
  protected loader: boolean;

  constructor(
    private rootStoreService: RootStoreService,
    private placementStoreService: PlacementStoreService,
  ) {
    this.loader = this.rootStoreService.loader;
  }

  ngOnInit(): void {
    this.rootStoreService.init().then((list: IList) => {
      this.placementStoreService.setList(list);
    });

    this.rootStoreService.appInfo().then(({ scope }: { scope: string[] }) => {
      this.verifyScopeLog(environment.SCOPE, scope);
    });
  }

  verifyScopeLog(scopeList: string[], requiredList: string[]) {
    [...scopeList, ...requiredList]
      .reduce((messages: string[], scope) => {
        if (!scopeList.includes(scope))
          messages.push(`scope "${scope}" excess`);
        if (!requiredList.includes(scope))
          messages.push(`scope "${scope}" not found`);
        return messages;
      }, [])
      .forEach((message: string) => {
        console.info('🔥', message);
      });
  }
}

@if (store.loader$ | async) {
  <app-loader></app-loader>
} @else {
  <app-user-lists></app-user-lists>
}

// templates/vue-template/src/views/HomePage.vue
<template>
  <the-loader v-if="loader" :loader="loader"></the-loader>
  <user-lists v-else></user-lists>
</template>

<script>
import { mapState, mapActions } from 'pinia';
import { useRootStore } from '@/stores/RootStore';
import { usePlacementStore } from '@/stores/PlacementStore';
import TheLoader from '../components/TheLoader.vue';
import UserLists from '../components/UserLists.vue';
import env from '../env';

export default {
  methods: {
    ...mapActions(useRootStore, ['init', 'appInfo']),
    ...mapActions(usePlacementStore, ['setList']),

    verifyScopeLog(scopeList, requiredList) {
      [...scopeList, ...requiredList].reduce((messages, scope) => {
        if (!scopeList.includes(scope)) messages.push(`scope "${scope}" excess`);
        if (!requiredList.includes(scope)) messages.push(`scope "${scope}" not found`);
        return messages;
      }, []).forEach((message) => {
        console.info('🔥', message);
      });
    },
  },
  computed: mapState(useRootStore, ['loader']),
  created() {
    this.appInfo().then((info) => {
      this.verifyScopeLog(env.get('SCOPE'), info.scope);
    });
  },
  mounted() {
    this.init()
      .then(this.setList)
      .catch(console.warn);
  },
  components: {
    TheLoader,
    UserLists,
  },
  name: 'home-page',
};
</script>
