// templates/ng-template/src/app/pages/settings-page/settings-page.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { GeneratorListComponent } from '../../components/generator-list/generator-list.component';
import { PlacementListComponent } from '../../components/placement-list/placement-list.component';
import { LinkComponent } from '../../components/link/link.component';
import { StoreService } from '../../services/store.service';

@Component({
  selector: 'app-settings-page',
  imports: [GeneratorListComponent, PlacementListComponent, LinkComponent],
  templateUrl: './settings-page.component.html',
  styleUrl: './settings-page.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SettingsPageComponent {
  protected store = inject(StoreService);
}

<div class="settings-page">
  <fieldset>
    <legend>Настройки портала</legend>
    <div class="settings-page__buttons">
      <app-link [href]="`/devops/edit/application/${store.appId}/`">
        <button>Настройки приложения</button>
      </app-link>
      <app-link href="/devops/section/standard/">
        <button>Создать приложение</button>
      </app-link>
      <app-link href="/devops/list/">
        <button>Все приложения</button>
      </app-link>
    </div>
  </fieldset>

  <fieldset>
    <legend>Генерация данных</legend>
    <app-generator-list></app-generator-list>
  </fieldset>

  <fieldset>
    <legend>Встраивание</legend>
    @if (store.scopeList.includes('placement') && store.isAdmin) {
      <app-placement-list></app-placement-list>
    } @else {
      <span>Нет прав</span>
    }
  </fieldset>
</div>

// templates/vue-template/src/views/SettingsPage.vue
<template>
  <div class="settings-page">
    <fieldset>
      <legend>Настройки портала</legend>
      <div class="settings-page__buttons">
        <app-link :href="`/devops/edit/application/${store.appId}/`">
          <bx-button icon="setting" size="xs">Настройки приложения</bx-button>
        </app-link>
        <app-link href="/devops/section/standard/">
          <bx-button icon="add" size="xs" color="primary-dark">Создать приложение</bx-button>
        </app-link>
        <app-link href="/devops/list/">
          <bx-button icon="list" size="xs" color="secondary">Все приложения</bx-button>
        </app-link>
      </div>
    </fieldset>

    <fieldset>
      <legend>Генерация данных</legend>
      <generator-list></generator-list>
    </fieldset>

    <fieldset>
      <legend>Встраивание</legend>
      <placement-list
        v-if="store.scopeList.includes('placement') && store.isAdmin"
      ></placement-list>
      <span v-else>Нет прав</span>
    </fieldset>
  </div>
</template>

<script setup lang="ts">
import { BxButton } from 'vue-bitrix24';
import { useRootStore } from '@/stores/RootStore';
import AppLink from '@/components/AppLink.vue';
import GeneratorList from '@/components/GeneratorList.vue';
import PlacementList from '@/components/PlacementList.vue';

const store = useRootStore();
</script>

<style lang="scss">
.settings-page {
  &__buttons > * + * {
    margin-left: 10px;
  }
}
</style>
