// templates/ng-template/src/app/dev/dev-panel-reload/dev-panel-reload.component.ts
import { Component } from '@angular/core';
import { BitrixService } from '../../services/bitrix.service';

@Component({
  selector: 'dev-panel-reload',
  standalone: true,
  imports: [],
  templateUrl: './dev-panel-reload.component.html',
  styleUrl: './dev-panel-reload.component.scss',
})
export class DevPanelReloadComponent {
  constructor(private bitrixService: BitrixService) {
    this.bitrixService.BX24.bind(window, 'keydown', (e: KeyboardEvent) => {
      if (e.ctrlKey && e.code === 'KeyR') {
        this.reload(e);
      }
    });
  }
  reload(e: Event) {
    e.preventDefault();
    window.location.reload();
  }
}

<a href="#" title="Обновить (Ctrl+R)" (click)="reload($event)">
  <ng-content></ng-content>
</a>

// templates/vue-template/src/components/dev/DevPanelReload.vue
<template>
  <a href="#" title="Обновить (Ctrl+R)" @click.prevent="reload">
    <slot></slot>
  </a>
</template>

<script setup lang="ts">
import { useBitrix24 } from '@/composable/bitrix';

const { BX24 } = useBitrix24();

BX24.bind(window, 'keydown', (e) => {
  if (e instanceof KeyboardEvent && e.ctrlKey && e.code === 'KeyR') {
    e.preventDefault();
    reload();
  }
});

function reload() {
  window.location.reload();
}
</script>
