// templates/vue2-template/src/components/UserList.vue
<template>
  <div v-if="show" class="user-list">
    <div class="user-list__wrapper">
      <h1>
        <a :href="portal" target="_blank">{{ domain }}</a>
      </h1>
      <div class="user-list__card" v-for="(user, id) in users" :key="id">
        <a
          class="user"
          :class="classList(id)"
          :href="`${portal}${user.href}`"
          :target="user.target"
          :title="getTitle(user)"
          :data-birthday="user.birthday"
          @click.prevent="openLink(user.href)"
        >
          <img v-if="user.photo" :src="user.photo" :alt="user.fullName">
        </a>
        <bx-button-wrapper center>
          <bx-button
            color="light-border"
            size="xs"
            :round="true"
            @click="openHistory(id)"
          >История</bx-button>
          <bx-button
            color="light-border"
            size="xs"
            icon="chat"
            :round="true"
            @click="openMessenger(id)"
          >Чат</bx-button>
        </bx-button-wrapper>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState, mapGetters } from 'vuex';

export default {
  methods: {
    classList(id) {
      return {
        department: this.department.includes(id),
        current: this.currentId === id,
      };
    },
    getTitle(user) {
      return [user.fullName, user.position].filter((s) => s).join('\n');
    },
    openLink(href) {
      this.$BX24.openLink(href);
    },
    openMessenger(id) {
      this.$BX24.im.openMessenger(id);
    },
    openHistory(id) {
      this.$BX24.im.openHistory(id);
    },
  },
  computed: {
    ...mapState(['users', 'department', 'currentId']),
    ...mapGetters(['domain', 'portal']),
    show() {
      return Object.keys(this.users).length;
    },
  },
  inject: ['$BX24'],
};
</script>

<style lang="stylus">
@import '~/src/assets/smartgrid';
size = 170px

.user-list
  wrapper()
  &__wrapper
    row-flex()
  &__card
    col()
    col-size(3)
    col-size-w1600(4)
    col-size-w1200(6)
  h1
    col()
    col-size(24)
    text-align center
    margin-bottom 20px
  a.user
    display block
    margin 0 auto
    width size
    height size
    border 5px solid black
    border-radius 50%
    background-image url("~@/assets/nouserpic.svg")
    background-color rgba(82,92,105,.23)
    background-size 111px 124px
    background-repeat no-repeat
    background-position center
    &.department
      border-color coral
    &.current
      border-color currentColor
    img
      display block
      object-fit cover
      width 100%
      height 100%
      border-radius 50%
      font-size 0
</style>

// templates/ng-template/src/app/components/user-list/user-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { BitrixService } from '../../services/bitrix.service';
import { RootStoreService } from '../../services/root-store.service';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [],
  templateUrl: './user-list.component.html',
  styleUrl: './user-list.component.scss',
})
export class UserListComponent implements OnInit {
  @Input({ required: true }) public users: IUsers;
  private department: any;
  private currentId: any;
  protected portal: any;

  constructor(
    private bitrixService: BitrixService,
    private rootStoreService: RootStoreService,
  ) {}

  ngOnInit() {
    this.department = this.rootStoreService.department;
    this.currentId = this.rootStoreService.currentId;
    this.portal = this.rootStoreService.portal;
  }

  getUsers(): IUser[] {
    return Object.values(this.users);
  }

  classList(id: string) {
    return {
      department: this.department.includes(id),
      current: this.currentId === id,
    };
  }

  getTitle(user: any) {
    return [user.fullName, user.position].filter((s) => s).join('\n');
  }

  openLink(e: MouseEvent, href: string) {
    e.preventDefault();
    this.bitrixService.BX24.openLink(href);
  }

  openMessenger(id: string) {
    this.bitrixService.BX24.im.openMessenger(id);
  }
}

<div class="user-list">
  @for (user of getUsers(); track user.id) {
    <div class="user-list__card">
      <a
        class="user"
        [class]="classList(user.id)"
        [href]="portal + user.href"
        [target]="user.target"
        [title]="getTitle(user)"
        [attr.data-birthday]="user.birthday"
        (click)="openLink($event, user.href)"
        style="background-image: url('assets/nouserpic.svg')"
      >
        @if (user.photo) {
          <img [src]="user.photo" [alt]="user.fullName" loading="lazy" />
        }
      </a>
      <div class="user-list__buttons">
        <button
          data-color="light-border"
          data-size="xs"
          data-icon="chat"
          data-round="true"
          (click)="openMessenger(user.id)"
        >
          Открыть чат
        </button>
      </div>
    </div>
  }
</div>
