// templates/vue3-template/src/components/dev/DevPanelReload.vue
<template>
  <a href="#" title="Обновить (Ctrl+R)" @click.prevent="reload">
    <span class="mdi mdi-reload"></span>
  </a>
</template>

<script>
export default {
  methods: {
    reload() {
      window.location.reload();
    },
  },
  created() {
    window.addEventListener('keydown', (e) => {
      if (e.ctrlKey && e.code === 'KeyR') {
        e.preventDefault();
        this.reload();
      }
    });
  },
  name: 'dev-panel-reload',
};
</script>

// templates/ng-template/src/app/dev/dev-panel-reload/dev-panel-reload.component.ts
import { Component } from '@angular/core';
import { BitrixService } from '../../services/bitrix.service';

@Component({
  selector: 'dev-panel-reload',
  standalone: true,
  imports: [],
  templateUrl: './dev-panel-reload.component.html',
  styleUrl: './dev-panel-reload.component.scss',
})
export class DevPanelReloadComponent {
  constructor(private bitrixService: BitrixService) {
    this.bitrixService.BX24.bind(window, 'keydown', (e: KeyboardEvent) => {
      if (e.ctrlKey && e.code === 'KeyR') {
        this.reload(e);
      }
    });
  }
  reload(e: Event) {
    e.preventDefault();
    window.location.reload();
  }
}

<a href="#" title="Обновить (Ctrl+R)" (click)="reload($event)">
  <ng-content></ng-content>
</a>
