// templates/vue3-template/src/components/UserLists.vue
<template>
  <div class="user-lists">
    <user-toggle @click="type = $event" :default-type="type"></user-toggle>
    <div class="user-lists__wrapper">
      <users-list
        v-if="type === 'users'"
        key="users"
        :users="usersEnabled"
      ></users-list>
      <users-list
        v-else-if="type === 'disabled'"
        key="disabled"
        :users="usersDisabled"
      ></users-list>
    </div>
  </div>
</template>

<script>
import { mapState } from 'pinia';
import { useRootStore } from '@/stores';
import UserToggle from './UserToggle.vue';
import UsersList from './UserList.vue';

export default {
  computed: {
    ...mapState(useRootStore, ['users']),

    usersEnabled() {
      const users = Object.entries(this.users).filter(([key, user]) => user.active);
      return Object.fromEntries(users);
    },

    usersDisabled() {
      const users = Object.entries(this.users).filter(([key, user]) => !user.active);
      return Object.fromEntries(users);
    },
  },
  data() {
    return {
      type: 'users',
    };
  },
  components: {
    UserToggle,
    UsersList,
  },
  name: 'user-lists',
};
</script>

<style lang="stylus">
@import '../src/assets/smartgrid';

.user-lists
  wrapper()
  &__wrapper
    margin-top 40px
</style>

// templates/ng-template/src/app/components/user-lists/user-lists.component.ts
import { Component } from '@angular/core';
import {
  UserToggleComponent,
  TType,
} from '../user-toggle/user-toggle.component';
import {
  UserListComponent,
  IUsers,
  IUser,
} from '../user-list/user-list.component';
import { RootStoreService } from '../../services/root-store.service';

@Component({
  selector: 'app-user-lists',
  standalone: true,
  imports: [UserToggleComponent, UserListComponent],
  templateUrl: './user-lists.component.html',
  styleUrl: './user-lists.component.scss',
})
export class UserListsComponent {
  public type: TType = 'users';

  constructor(private rootStore: RootStoreService) {}

  get usersEnabled(): IUsers {
    const list = Object.entries(this.rootStore.users as IUsers).filter(
      ([_key, user]: [string, IUser]) => user.active,
    );
    return Object.fromEntries(list);
  }

  get usersDisabled(): IUsers {
    const list = Object.entries(this.rootStore.users as IUsers).filter(
      ([_key, user]: [string, IUser]) => !user.active,
    );
    return Object.fromEntries(list);
  }

  setType(type: TType) {
    this.type = type;
  }
}

<div class="user-lists">
  <app-user-toggle (click)="setType($event)"></app-user-toggle>
  <div class="user-lists__wrapper">
    @if (type === 'users') {
      <app-user-list [users]="usersEnabled"></app-user-list>
    } @else if (type === 'disabled') {
      <app-user-list [users]="usersDisabled"></app-user-list>
    }
  </div>
</div>
