// templates/ng-template/src/app/components/form-validation/form-validation.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-form-validation',
  imports: [ReactiveFormsModule],
  templateUrl: './form-validation.component.html',
  styleUrl: './form-validation.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FormValidationComponent {
  form: FormGroup = new FormGroup({
    name: new FormControl(null, Validators.required),
    email: new FormControl(null, [Validators.required, Validators.email]),
    password: new FormControl(null, [Validators.required, Validators.minLength(8)]),
  });

  onSubmit() {
    console.log(this.form.value);
  }
}

<form class="form-validation" [formGroup]="form" (ngSubmit)="onSubmit()">
  <fieldset>
    <legend>Форма с валидацией</legend>
    <div class="form-error-wrapper">
      <input formControlName="name" type="text" placeholder="Имя" />
      @if (form.get('name')?.invalid && form.get('name')?.touched) {
        <div class="form-error-wrapper__error">
          @if (form.get('name')?.errors?.['required']) {
            <small>Поле обязательное!</small>
          }
        </div>
      }
    </div>
    <div class="form-error-wrapper">
      <input formControlName="email" type="text" placeholder="Электронная почта" />
      @if (form.get('email')?.invalid && form.get('email')?.touched) {
        <div class="form-error-wrapper__error">
          @if (form.get('email')?.errors?.['required']) {
            <small>Поле обязательное!</small>
          }
          @if (form.get('email')?.errors?.['email']) {
            <small>Не email!</small>
          }
        </div>
      }
    </div>
    <div class="form-error-wrapper">
      <input formControlName="password" type="text" placeholder="Пароль" />
      @if (form.get('password')?.invalid && form.get('password')?.touched) {
        <div class="form-error-wrapper__error">
          @if (form.get('password')?.errors?.['required']) {
            <small>Поле обязательное!</small>
          }
          @if (form.get('password')?.errors?.['minlength']) {
            <small>
              Не менее
              {{ form.get('password')?.errors?.['minlength']['requiredLength'] }}
              символов!
            </small>
          }
        </div>
      }
    </div>
    <div class="form-validation__buttons">
      <button type="reset">Сбросить</button>
      <button type="submit" [disabled]="form.invalid">Отправить</button>
    </div>
  </fieldset>
</form>

// templates/vue-template/src/components/FormValidation.vue
<template>
  <form class="form-validation" @reset="onReset" @submit.prevent="onSubmit" style="width: 100%">
    <fieldset>
      <legend>Форма с валидацией</legend>
      <form-error-wrapper :errors="v$.form.email.$errors">
        <bx-input
          v-model="v$.form.email.$model"
          :color="v$.form.email.$error ? 'danger' : ''"
          placeholder="Почта"
        ></bx-input>
      </form-error-wrapper>
      <form-error-wrapper :errors="v$.form.password.$errors">
        <bx-input
          v-model="v$.form.password.$model"
          :color="v$.form.password.$error ? 'danger' : ''"
          placeholder="Пароль"
          type="password"
        ></bx-input>
      </form-error-wrapper>
      <form-error-wrapper :errors="v$.form.passwordConfirm.$errors">
        <bx-input
          v-model="v$.form.passwordConfirm.$model"
          :color="v$.form.passwordConfirm.$error ? 'danger' : ''"
          placeholder="Подтвердите пароль"
        ></bx-input>
      </form-error-wrapper>
      <div class="form-validation__buttons">
        <bx-button type="reset" color="light-border">Сбросить</bx-button>
        <bx-button type="submit" :disabled="v$.$error">Отправить</bx-button>
      </div>
    </fieldset>
  </form>
</template>

<script setup lang="ts">
import { reactive, computed, provide, type Ref } from 'vue';
import { useVuelidate, type Validation } from '@vuelidate/core';
import { email, required, minLength, sameAs, helpers } from '@vuelidate/validators';
import FormErrorWrapper from './FormErrorWrapper.vue';

provide('$BX24', null);

const data = reactive({
  form: {
    email: '',
    password: '',
    passwordConfirm: '',
  },
});

const rules = computed(() => ({
  form: {
    email: {
      required: helpers.withMessage('Заполните это поле', required),
      email: helpers.withMessage('Неверный адрес эл. почты', email),
    },
    password: {
      required: helpers.withMessage('Заполните это поле', required),
      minLength: helpers.withMessage('Пароль должен быть не менее 8 символов', minLength(8)),
    },
    passwordConfirm: {
      required: helpers.withMessage('Заполните это поле', required),
      sameAs: helpers.withMessage('Пароли не совпадают', sameAs(data.form.password)),
    },
  },
}));

const v$: Ref<Validation> = useVuelidate(rules, data);

function onReset() {
  data.form.email = '';
  data.form.password = '';
  data.form.passwordConfirm = '';
  v$.value.$reset();
}

function onSubmit() {
  v$.value.$touch();
  if (v$.value.$error) return;
  console.info({
    email: data.form.email,
    password: btoa(data.form.password),
  });
}
</script>

<style lang="scss">
.form-validation {
  input {
    width: 100%;
  }

  &__buttons {
    text-align: right;

    [type='submit'] {
      margin-left: 10px;
    }
  }
}
</style>
