// templates/ng-template/src/app/components/placement-list/placement-list.component.ts
import { ChangeDetectorRef, ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LinkComponent } from '../link/link.component';
import { StoreService } from '../../services/store.service';

@Component({
  selector: 'app-placement-list',
  imports: [FormsModule, LinkComponent],
  templateUrl: './placement-list.component.html',
  styleUrl: './placement-list.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlacementListComponent {
  private cdr = inject(ChangeDetectorRef);
  protected store = inject(StoreService);

  get list(): IPlacement[] {
    return Object.values(this.store.placementList);
  }

  get link() {
    return this.store.appLink;
  }

  async bind(item: { placement: string; name: string; bind: boolean }) {
    await this.store.bind(item);
    this.cdr.markForCheck();
  }

  async unbind(placement: string) {
    await this.store.unbind(placement);
    this.cdr.markForCheck();
  }
}

<table class="placement-list">
  @for (item of list; track $index) {
    <tbody>
      @if (item.placement === 'CRM_DEAL_DETAIL_TAB') {
        <tr>
          <td colspan="3">
            @if (store.scopeList.includes('crm')) {
              <small>Scope: crm</small>
            } @else {
              <small class="error">Scope: crm не подключен</small>
            }
          </td>
        </tr>
      }
      @if (item.placement !== 'REST_APP_URI' && !store.scopeList.includes('crm')) {
        <tr></tr>
      } @else if (item.bind) {
        <tr>
          <td>
            <small>{{ item.placement }}</small>
          </td>
          <td>
            @if (item.placement === 'REST_APP_URI') {
              <app-link [href]="link">
                {{ item.name }}
              </app-link>
            } @else if (item.placement === 'CRM_ANALYTICS_MENU') {
              <app-link href="/report/analytics/">
                {{ item.name }}
              </app-link>
            } @else if (item.placement === 'CRM_DEAL_DETAIL_TAB') {
              <app-link href="/crm/deal/list/">
                {{ item.name }}
              </app-link>
            } @else {
              <span>{{ item.name }}</span>
            }
          </td>
          <td>
            <button (click)="unbind(item.placement)">Удалить</button>
          </td>
        </tr>
      } @else {
        <tr>
          <td>
            <small>{{ item.placement }}</small>
          </td>
          <td>
            <input
              [(ngModel)]="item.name"
              [placeholder]="item.placement"
              [disabled]="item.placement === 'REST_APP_URI'"
            />
          </td>
          <td>
            <button [disabled]="!item.name" (click)="bind(item)">Добавить</button>
          </td>
        </tr>
      }
    </tbody>
  }
</table>

// templates/vue-template/src/components/PlacementList.vue
<template>
  <table class="placement-list">
    <tbody v-for="(item, key) in placementList" :key="key">
      <tr v-if="item.bind">
        <td>
          <small>{{ item.placement }}</small>
        </td>
        <td>
          <app-link v-if="item.placement === 'REST_APP_URI'" :href="placementLink">
            {{ item.name }}
          </app-link>
          <app-link v-else-if="item.placement === 'CRM_ANALYTICS_MENU'" href="/report/analytics/">
            {{ item.name }}
          </app-link>
          <app-link v-else-if="item.placement === 'CRM_DEAL_DETAIL_TAB'" href="/crm/deal/list/">
            {{ item.name }}
          </app-link>
          <span v-else>{{ item.name }}</span>
        </td>
        <td>
          <bx-button color="danger" @click="unbind(item.placement)">Удалить</bx-button>
        </td>
      </tr>
      <tr v-else>
        <td>
          <small>{{ item.placement }}</small>
        </td>
        <td>
          <bx-input v-model="item.name" :placeholder="item.placement" inline></bx-input>
        </td>
        <td>
          <bx-button :disabled="!item.name" color="primary" @click="bind(item)">Добавить</bx-button>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { BxButton, BxInput } from 'vue-bitrix24';
import { usePlacementStore } from '@/stores/PlacementStore';
import AppLink from './AppLink.vue';

const placementStore = usePlacementStore();

const placementList = computed(() => placementStore.placementList);
const placementLink = computed(() => placementStore.appLink);

function bind(item: IPlacement) {
  placementStore.bind(item);
}

function unbind(placement: string) {
  placementStore.unbind(placement);
}
</script>

<style lang="scss">
.placement-list small {
  color: gray;
}
</style>
