// templates/vue-template/src/components/dev/DevPanelDownload.vue
<template>
  <a
    :href="dirname"
    :download="filename"
    title="Скачать последнюю версию"
  >
    <span class="mdi mdi-download"></span>
  </a>
</template>

<script>
import config from '../../config';

export default {
  computed: {
    dirname() {
      return [config.path, this.filename].join('');
    },
    filename() {
      return `${config.global.appDirName}, ${new Date().toLocaleString()}.zip`;
    },
  },
  name: 'dev-panel-download',
};
</script>

// templates/ng-template/src/app/dev/dev-panel-download/dev-panel-download.component.ts
import { Component } from '@angular/core';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'dev-panel-download',
  standalone: true,
  imports: [],
  templateUrl: './dev-panel-download.component.html',
  styleUrl: './dev-panel-download.component.scss',
})
export class DevPanelDownloadComponent {
  filename: string = `${environment.APP_NAME}, ${new Date().toLocaleString()}.zip`;
  dirname: string = [
    environment.PATH_HANDLER,
    `${environment.APP_NAME}.zip`,
  ].join('');
}

<a [href]="dirname" [download]="filename" title="Скачать последнюю версию">
  <ng-content></ng-content>
</a>
